INSERT INTO quizzes (quiz, answer) VALUES (1, 'who lives in victoria?', 'amy', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'which day did this cohort kick-off?', '0404', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'who is the most handsome guy at LHL?', 'andy', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'which guy has the longest hair in the cohort?', 'robbie', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'who was a commercial truck driver before the course?', 'jason', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'who worked in dental in the cohort?', 'ana', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'which island does Nally live on?','galiano', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'who is the semicolon police in the cohort?', 'jordan', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'what was our first project?', 'tinyapp', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'how many girls do we have in the cohort?','5', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'who is a dad of 3 kids in the cohort?', 'darren', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'who always stays in the voice channel alone', 'aaron D', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'who is a rock climber in the cohort?', 'nicolas', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'who is the Einstein in the cohort?', 'jc', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'who was modelling for a Korean dashcam company before?', 'aidan', 'true');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'who worked as a QA before?', 'moon');
INSERT INTO quizzes (quiz, answer) VALUES (1, 'which instructor supervises our friday exams?', 'david', 'true');
