INSERT INTO quizzes (quiz) VALUES ('who lives in victoria?');
INSERT INTO quizzes (quiz) VALUES ('which day did this cohort kick-off?');
INSERT INTO quizzes (quiz) VALUES ('who is the most handsome guy at LHL?');
INSERT INTO quizzes (quiz) VALUES ('which guy has the longest hair in the cohort?');
INSERT INTO quizzes (quiz) VALUES ('who was a commercial truck driver before the course?');
INSERT INTO quizzes (quiz) VALUES ('who worked in dental in the cohort?');
INSERT INTO quizzes (quiz) VALUES ('which island does Nally live on?');
INSERT INTO quizzes (quiz) VALUES ('who is the semicolon police in the cohort?');
INSERT INTO quizzes (quiz) VALUES ('what was our first project?');
INSERT INTO quizzes (quiz) VALUES ('how many girls do we have in the cohort?');
INSERT INTO quizzes (quiz) VALUES ('who is a dad of 3 kids in the cohort?');
INSERT INTO quizzes (quiz) VALUES ('who always stays in the voice channel alone');
INSERT INTO quizzes (quiz) VALUES ('who is a rock climber in the cohort?');
INSERT INTO quizzes (quiz) VALUES ('who is the Einstein in the cohort?');
INSERT INTO quizzes (quiz) VALUES ('who was modelling for a Korean dashcam company before?');
INSERT INTO quizzes (quiz) VALUES ('who worked as a QA before?');
INSERT INTO quizzes (quiz) VALUES ('which instructor supervises our friday exams?');
