INSERT INTO quizzes (quiz, answer) VALUES ('who lives in victoria?', 'amy');
INSERT INTO quizzes (quiz) VALUES ('which day did this cohort kick-off?', '0404');
INSERT INTO quizzes (quiz) VALUES ('who is the most handsome guy at LHL?', 'andy');
INSERT INTO quizzes (quiz) VALUES ('which guy has the longest hair in the cohort?', 'robbie');
INSERT INTO quizzes (quiz) VALUES ('who was a commercial truck driver before the course?', 'jason');
INSERT INTO quizzes (quiz) VALUES ('who worked in dental in the cohort?', 'ana');
INSERT INTO quizzes (quiz) VALUES ('which island does Nally live on?','galiano');
INSERT INTO quizzes (quiz) VALUES ('who is the semicolon police in the cohort?', 'jordan');
INSERT INTO quizzes (quiz) VALUES ('what was our first project?', 'tinyapp');
INSERT INTO quizzes (quiz) VALUES ('how many girls do we have in the cohort?','5');
INSERT INTO quizzes (quiz) VALUES ('who is a dad of 3 kids in the cohort?', 'darren');
INSERT INTO quizzes (quiz) VALUES ('who always stays in the voice channel alone', 'aaron D');
INSERT INTO quizzes (quiz) VALUES ('who is a rock climber in the cohort?', 'nicolas');
INSERT INTO quizzes (quiz) VALUES ('who is the Einstein in the cohort?', 'jc');
INSERT INTO quizzes (quiz) VALUES ('who was modelling for a Korean dashcam company before?', 'aidan');
INSERT INTO quizzes (quiz) VALUES ('who worked as a QA before?', 'moon');
INSERT INTO quizzes (quiz) VALUES ('which instructor supervises our friday exams?', 'david');
